apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: username
  RABBITMQ_DEFAULT_PASS: password
  ORDER_QUEUE_USERNAME: username
  ORDER_QUEUE_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-gpt-api-secret
type: Opaque
stringData:
  OPENAI_GPT_API_KEY: "dummy-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-dalle-api-secret
type: Opaque
stringData:
  OPENAI_DALLE_API_KEY: "dummy-key"
